const HOUSE_EDGE_FEE = 0.01;
const ELO_TOKENS_SHARE = 0.01;

module.exports = {
  HOUSE_EDGE_FEE: HOUSE_EDGE_FEE,
  ELO_TOKENS_SHARE: ELO_TOKENS_SHARE,
  FEE_MULTIPLIER: 1 - HOUSE_EDGE_FEE - ELO_TOKENS_SHARE,
  MATCHES_PER_PAGE: 20
};
